version: "3"

services:

  db-product:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: product123
      POSTGRES_USER: productuser
      POSTGRES_DB: productmydb
    networks:
      - productnetwork

  e-shop-product:
    build:
      context: .
      dockerfile: product/Dockerfile
    environment:
      DB_PORT: 5432
      DB_DB: productmydb
      DB_USER: productuser
      DB_PASSWORD: product123
      DB_HOST: db-product
      AUTH_PORT: 8081
      AUTH_HOST: e-shop-auth
    depends_on:
      - db-product
      - e-shop-auth
    ports:
      - "8080:8080"
    networks:
      - productnetwork
      - authproductnetwork

  db-auth:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: auth123
      POSTGRES_USER: authuser
      POSTGRES_DB: authmydb
    networks:
      - authnetwork

  e-shop-auth:
    build:
      context: .
      dockerfile: auth/Dockerfile
    environment:
      DB_PORT: 5432
      DB_DB: authmydb
      DB_USER: authuser
      DB_PASSWORD: auth123
      DB_HOST: db-auth
    ports:
      - "8081:8081"
    depends_on:
      - db-auth
    networks:
      - authnetwork
      - authproductnetwork

networks:
  productnetwork:
  authnetwork:
  authproductnetwork:
