version: "3"

services:

  db:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: user
      POSTGRES_DB: mydb
    networks:
      - mynetwork

  app:
    build: .
    environment:
      DB_PORT: 5432
      DB_DB: mydb
      DB_USER: user
      DB_PASSWORD: 123
      DB_HOST: db
    ports:
      - "8080:8080"
    networks:
      - mynetwork

networks:
  mynetwork:
